### ISSUE TITLE
현재의 타입 활성화

### ISSUE THREAD

**Issue by redgoose-dev** [redgoose-dev/json-editor#19]
노드 메뉴에서 타입을 고를때 현재 무슨타입인지 알수가 없다.
그래서 배경색으로 현재의 타입이 어떤건지 구분을 해줄 필요가 있어보인다.

**Comment by easylogic** [comment]
타입은   각  타입이름의 이니셜  첫글자로 해보는건 어떨까요? 

A : Array 
O  : Object 
S  : String 
N : Number 
U : undefined 
- : null 
D : Date

**Comment by RedgooseDev** [comment]
목록에서 이니셜 아이콘으로 표시되는게 좋겠네요.
메뉴에서 활성화되어있는 타입의 표시만 생각하고 있었는데 트리에서 바로 확인이 가능하다면 더 직관적일거 같아요 ㅎㅎ

**Comment by redgoose-dev** [comment]
다음 버전에서 적용예정

**Comment by redgoose-dev** [comment]
1.0 버전에서 적용예정
